# Generated by Django 5.2.6 on 2025-09-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('consumo', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ['uid', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Generación',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('generacion', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
